language: ruby
rvm:
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9"
  - "1.8"
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rack-1.x
before_install:
  - gem update bundler
matrix:
  exclude:
    - { gemfile: Gemfile, rvm: "2.1" }
    - { gemfile: Gemfile, rvm: "2.0" }
    - { gemfile: Gemfile, rvm: "1.9" }
    - { gemfile: Gemfile, rvm: "1.8" }
