language: ruby
rvm:
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
  - "2.2"
  - "2.1"
  - "2.0"
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rack-1.x
before_install:
  - gem update bundler
matrix:
  exclude:
    - { rvm: "2.1", gemfile: Gemfile }
    - { rvm: "2.0", gemfile: Gemfile }
  include:
    - { rvm: "1.8.7", dist: precise, gemfile: gemfiles/Gemfile.rack-1.x }
    - { rvm: "1.9.3", dist: trusty,  gemfile: gemfiles/Gemfile.rack-1.x }
