language: ruby
rvm:
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
  - "2.2"
  - "2.1"
  - "2.0"
gemfile:
  - gemfiles/Gemfile.rack-1.x
  - gemfiles/Gemfile.rack-2.x
before_install:
  - gem update bundler
matrix:
  exclude:
    - { gemfile: gemfiles/Gemfile.rack-2.x, rvm: "2.1" }
    - { gemfile: gemfiles/Gemfile.rack-2.x, rvm: "2.0" }
